[팀 서비스 클론 코딩] 도담(김민재) 미션 제출합니다.
woowacourse/frontend-rendering pull request #13
Opened 2023-10-11 02:07 UTC by D0Dam

# 🎨 1단계 - 팀 서비스의 일부 페이지 클론 코딩

## 🚀 구현한 페이지의 주소와 방식
- 주소: []()
- 렌더링 방식: SSR / SSG / ISR 중 선택

## ✅ 체크리스트

### 선택한 렌더링 방식의 이유
- [ ] 선택한 렌더링 방식이 어떤 페이지에 적합한지, 왜 선택했는지 이유 설명

### 코드 재사용
- [ ] 기존 서비스에서 구현한 리액트 컴포넌트의 재사용 여부와 활용 방식에 대해 설명

# 🧐 2단계 - 렌더링 방식의 분석

## ✅ 체크리스트

### 렌더링 시점 비교
- [ ] SPA와 본인이 선택한 렌더링 방식(SSR, SSG, ISR) 중 본인이 선택한 방식간의 렌더링 시점에 어떤 일이 벌어지는지 설명 (그림 또는 다이어그램 활용도 좋습니다)

### 사용자 경험(UX) 측면 분석
- [ ] 각 렌더링 방식이 사용자 경험에 어떻게 영향을 미치는지 설명

### 성능 측정 및 비교
- [ ] SPA와 본인이 선택한 렌더링 방식(SSR, SSG, ISR)의 성능을 측정하고 비교 (사용한 측정 도구나 방법을 명시)

# 📝 리뷰어를 위한 가이드라인
이번 미션의 핵심 경험은 'Next.js와 프론트엔드에서의 렌더링'을 이해하고 자신의 프로젝트에 적용해보는 것입니다. 이 목표를와 함께 아래 가이드라인을 참고 후 개선을 위한 피드백을 남겨주세요

### 사용자로서, 페이지의 기능을 잘 사용할 수 있는지 학인해주세요,
- [ ] **사용성**: 클론 코딩한 페이지가 원본 페이지와 동일하게 작동하는 지 확인합니다. 의도한 페이지의 기능이 정상적으로 동작하며, 사용자 인터랙션에 따른 반응(예: hover 상태 등)도 잘 구현되었는 지 점검합니다. 이를 통해 사용자에게 어떤 경험이 더 최적화 될 수 있는지를 피드백해주세요.

### Next.js에서 제공하는 기능을 적극적으로 활용했는지 확인해 주세요 
> 아래 가이드라인 외에도 Next.js가 제공하는 기능에 대해 피드백 남겨주세요.
- [ ] **데이터 요청**: getServerSideProps나 getStaticProps 같은 데이터 fetching 함수를 올바르게 사용했는지 확인합니다.
- [ ] **파일 기반 라우팅**: Next.js의 파일 기반 라우팅 시스템을 잘 활용했는지 점검합니다.
- [ ] **에러 핸들링**: 네트워크 요청 실패나 예외 처리 등 에러 상황에서 앱이 적절히 반응하는지 파악합니다. 예를 들어 잘못된 URL 경로로 접근 시 404 페이지를 보여주는 등의 에러 핸들링을 확인해봅니다.

2023-10-11 15:30 UTC, shackstack requested changes
도담! 저희 프로젝트코드를 제가 리뷰하게되었군요ㅋㅋ
저와 다른방식으로 구현을 해서 배울점이 많았습니다.
몇 가지 질문과 함께 코멘트 남겼으니 확인해주세요! 


---

### 📝 질문 

> 저희 서비스의 경우 이동해야할 페이지와 페이지별 상태 변동이 꽤 있다고 생각했습니다.
그리고 SEO 가 이루어질 시 메인 페이지 뿐만 아니라 다른 map, detail 페이지 등도 SEO 를 적용할 필요가 있다고 생각해 SSR을 생각했습니다.

SSR을 겨냥하셨다면 제 생각으로는 빌드시에는 api 요청을 보내지 않고 사용자가 페이지에 방문하는 시점에 서버에서 api를 요청을 보내어 렌더링이 되어야한다고 봐요.
그러나 도담이 진행해주신 미션코드를 빌드하면 빌드결과물에 api요청 결과물이 포함되어있는데 이게 SSR이 맞을까요? 

> 기존 서비스에서 구현한 리액트 컴포넌트의 재사용 여부와 활용 방식에 대해 설명
그대로 가져와서 scss 와 css module 방식을 사용했습니다.



scss 와 css module 방식을 사용하신 이유가 궁금하네요!

2023-10-11 15:30 UTC, shackstack commented on src/app/not-found.tsx
오호 Not Found 페이지도 구현해주셨군요👍

2023-10-11 15:30 UTC, shackstack commented on src/components/MiniRestaurantCard/index.tsx
> +  const rating = 5;
fetch해서 사용할 수 있지 않을까요?

2023-10-11 15:30 UTC, shackstack commented on src/components/MiniRestaurantCard/index.tsx
> +  const { id, images, name, roadAddress, category } = restaurant;
```suggestion
function MiniRestaurantCard({ restaurant : { id, images, name, roadAddress, category }, celebs }: MiniRestaurantCardProps) {
```
이렇게 줄일 수도 있을 것 같네요.

2023-10-11 15:30 UTC, shackstack commented on src/app/api/celebs/route.ts
> +import { NextResponse } from "next/server";
NextResponse는 어디서 사용하는 건가요?

2023-10-13 03:57 UTC, D0Dam commented on src/components/MiniRestaurantCard/index.tsx
> +  const rating = 5;
여기에서 fetch를 어떤 식을 생각했을까요..?
혹시 음식점 정보에 대한 fetch라면 app의 Page.tsx 에서 fetch 해오고 있습니다!

2023-10-13 03:58 UTC, D0Dam commented on src/components/MiniRestaurantCard/index.tsx
> +  const { id, images, name, roadAddress, category } = restaurant;
오홍 그러네요! 바꿔보겠습니다~!

2023-10-13 04:00 UTC, D0Dam commented on src/app/api/celebs/route.ts
> +import { NextResponse } from "next/server";
헉! 코드를 수정하는 과정에서 삭제하는 걸 놓쳤나봅니다.. 삭제해 놓겠습니다!

2023-10-14 04:48 UTC, shackstack approved these changes
도담 잘 반영해주셨군요! 
피드백 남겨드린 부분 확인해주세요!

2023-10-14 04:48 UTC, shackstack commented on src/components/MiniRestaurantCard/index.tsx
> +  const rating = 5;
하드코딩 값을 사용하고 있는 rating 대해서 말씀드린거에요!
rating에 대한 값도 restaurant 객체에 담겨오지 않나요?

2023-10-14 05:37 UTC, D0Dam commented on src/components/MiniRestaurantCard/index.tsx
> +  const rating = 5;
아하! 그런 말씀이셨군요! 데이터가 아무래도 백엔드에서 전달되지 않았을 때의 데이터를 가져와서 이렇게 넣어 놓았습니다..!

2023-10-14 06:56 UTC, merged