[팀 서비스 클론 코딩] 타미(김태은) 미션 제출합니다.
woowacourse/frontend-rendering pull request #16
Opened 2023-10-11 04:51 UTC by xodms0309

# 🎨 1단계 - 팀 서비스의 일부 페이지 클론 코딩

## 🚀 구현한 페이지의 주소와 방식
- 주소:[가짜펀잇](https://frontend-rendering-tami.vercel.app/)
- [찐펀잇](https://funeat.site)
- 렌더링 방식: SSR

### 선택한 렌더링 방식의 이유
안녕하세요 에이든~ 만나서 반갑습니다
저는 홈화면을 SSR로 구현해봤는데요 그 이유는
1) SEO
2) 홈화면의 랭킹은 실시간으로 변할 가능성이 있기
때문입니다.
홈에 있는 세 가지 랭킹 중 상품을 제외하고는 기간에 대한 가중치를 계산해서 랭킹이 갱신이 됩니다. 사용자수가 적은 상황에서는 거의 변하지 않는 데이터지만 어째튼 변할 가능성이 있다고 해서 SSR을 선택하게 되었습니다.
저는 next 12버전까지만 사용해봤고 13의 app router는 처음인데 server component, client component에 대한 개념을 이해하는 것이 힘들었던 것 같아요.. 🥹 확실히 새로운 최신 버전이라 레퍼런스도 많이 없어서 힘들더라고요..ㅋㅋ 
그리고 async component를 써보려고 했는데 typescript 충돌이 생기더라고요.. 찾아보니까 5.1.3 버전 이상을 사용하라고 했는데 버전을 바꿔도 같은 오류가 뜨길래 일단 패스 했습니다. 미션 구현하는 시간보다는 어떤 렌더링 방법이 서비스에 적합할까 고민해보는 시간이 더 길었던 것 같습니다. SSR을 쓰니까 초기 로딩이 확실히 빠른 것 같긴 한데 이게 코드량이 적어서 그런지 SSR 때문인지는 잘 모르겠습니다.🤔 아무튼 리뷰 잘 부탁드립니다 ~.~

### 코드 재사용
그대로 데려오면서 react query랑 styled-components만 제거했습니다!

2023-10-13 04:58 UTC, gyeongza requested changes
타미 안녕하세요 ~ 리뷰하게 되어서 영광입니다 ㅎㅎ

저도 이번에 next를 처음 사용해봐서 많이 아는 부분은 없지만 그래도 학습한 부분 내에서는 최선을 다해보겠습니다..

- **사용성**: 진짜 펀잇 사이트인줄 알고 헷갈렸네요🤭 말씀해주신 것처럼 실제 펀잇 사이트와 비교하려고 해도 리소스도 다르고 최적화 정도도 다르기 때문에 정량화된 비교는 하기 힘들겠지만 나중에 필요한 부분을 실제 서비스에 적용해볼 수 있지 않을까요? 

- **데이터 요청**: 각 api 요청들을 서버 컴포넌트로 구현해주셨네요 ! fetch options에 cache 설정 no-store로 해주지 않으면 서버 데이터가 바뀌더라도 캐싱때문에 반영되지 않는다고 합니다. 저도 적용해야 되는 부분이긴 한데 여기에서 SSR/SSG의 개념이 갈리는 것 같습니다.

- **에러 핸들링**: 404페이지와 에러페이지를 잘 만들어 주신 것 같습니다. 저는 적용을 못했었는데 배워갑니다 👍

나머지 궁금한 부분들은 코멘트로 남겨드렸으니 확인부탁해요~ :)

2023-10-13 04:58 UTC, gyeongza commented on next.config.js
> +        pathname: `${process.env.NEXT_PUBLIC_IMAGE_PATHNAME}/*`,
로컬에서 실행시 환경변수가 없다고 나오는데요,

<img width="735" alt="스크린샷 2023-10-13 오전 10 39 11" src="https://github.com/woowacourse/frontend-rendering/assets/62369936/b3b27307-7aed-437c-8822-fc499bca6928">

만약 다른 사람이 테스트하는 환경이라면 
.env.local.example 과 같이 환경변수 샘플 파일 만들어서 올려주면 테스트하기 편할 것 같아요!

[관련영상](https://youtu.be/IFBMrrBjbfM?si=POndRlIJqoHLu4qM&t=347)

2023-10-13 04:58 UTC, gyeongza commented on src/app/not-found.tsx
> +}
<img width="300" alt="스크린샷 2023-10-13 오전 11 14 06" src="https://github.com/woowacourse/frontend-rendering/assets/62369936/d29354a0-83c0-48f1-b7ae-949de5d83b24">

👍👍

2023-10-13 04:58 UTC, gyeongza commented on src/app/page.tsx
> +        <RecipeRankingList recipes={recipes} />
<img width="628" alt="스크린샷 2023-10-13 오전 11 18 28" src="https://github.com/woowacourse/frontend-rendering/assets/62369936/4a839fbe-b03d-4b05-ab8d-8ff5c3e10b5b">

이 부분은 레이아웃 시프트가 일어나는데 원래 스타일이 이렇게 되어있는건가용?
진짜 펀잇은 suspense가 적용되어 있어서 괜찮은 것 같더라구요

2023-10-13 04:58 UTC, gyeongza commented on src/apis/fetchCategory.ts
> +export const fetchCategory = (categoryType: CategoryType) => {
해당 파일명만 fetchCategory로 네이밍 한 이유가 있나요??

2023-10-13 04:58 UTC, gyeongza commented on src/app/page.tsx
> +        <RecipeRankingList recipes={recipes} />
확인해보니 클라이언트 컴포넌트라 js가 불러와지기 전까지 width값과 translateX값을 계산하지 못해서 그런것 같네요! 이건 어떻게 해결해 볼 수 있을까용 ??

2023-10-15 08:40 UTC, xodms0309 commented on next.config.js
> +        pathname: `${process.env.NEXT_PUBLIC_IMAGE_PATHNAME}/*`,
오 이런방법이..

2023-10-15 08:42 UTC, xodms0309 commented on src/apis/fetchCategory.ts
> +export const fetchCategory = (categoryType: CategoryType) => {
그러게요..? 왜 이랫을까요...?ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-10-15 11:49 UTC, xodms0309 commented on src/app/page.tsx
> +        <RecipeRankingList recipes={recipes} />
nextjs에서 window객체를 사용하기 위해서 할 수 있는 몇 가지 방법들이 있는데요! 제가 일단 선택한 것은 useEffect를 사용한 것이었습니다. 그런데 그래도 CLS가 발생하더라고요...? 🥹 그래서 dynamic import를 사용해서 `ssr: false` 옵션을 주면 해당 컴포넌트에는 ssr이 적용 안되게 했습니다! (제출 할 때는 타입오류가 나서 포기했는데 다시 해보니까 되네요🤔) 그리고 로딩 ui를 추가해서 그 간극을 좀 낮췄습니다

2023-10-15 11:54 UTC, xodms0309 commented
주말 잘 보내셨나요 에이든~~ 주신 코멘트 기반으로 수정해봤습니다!
- [x] env.local.example 파일 추가
- [x] fetchCategory.ts -> category.ts로 파일명 수정
- [x] 캐러셀 dynamic import로 수정
- [x] fetch 함수에 cache: no-store 옵션 추가
꼼꼼한 리뷰 감사합니다 👍

2023-10-16 03:59 UTC, gyeongza approved these changes
리뷰 반영 확인했습니다 타미 ~ 고생하셨어요 ! step2도 화이팅입니다 :)

2023-10-16 04:00 UTC, merged