[팀 서비스 클론 코딩] 부엉이(이승환) 미션 제출합니다.
woowacourse/frontend-rendering pull request #25
Opened 2023-10-11 05:59 UTC by sh981013s

안녕하세요 유스!!!!!!! 잘 부탁드립니다 🙇‍♂️

# 🎨 1단계 - 팀 서비스의 일부 페이지 클론 코딩

## 🚀 구현한 페이지의 주소와 방식
- 주소: [https://frontend-rendering-4rx3krz93-sh981013s.vercel.app/](https://frontend-rendering-4rx3krz93-sh981013s.vercel.app/)
- 렌더링 방식: SSR 🔥

## ✅ 체크리스트

### 선택한 렌더링 방식의 이유
- [x] 선택한 렌더링 방식이 어떤 페이지에 적합한지, 왜 선택했는지 이유 설명

이번 미션에서 저는 [코끼리끼리 로드맵 리스트 페이지](https://kirikiri.lol/roadmap-list) 를 클론 코딩했습니다!  다양한 렌더링 방식도 몰랐고, Next 도 처음써보는 지라 많이 헤메었어요! 

고민한 결과, 저희 코끼리끼리 운영진측에서 로드맵을 제공할 수 있지만, 유저또한 로드맵을 생성하여 리스트에 포함하게 할 수 있기에 변동성이 많은 페이지 뷰라고 생각했습니다. 그렇기에 다른 방식인 ISR 과 SSG 는 적합하지 않다 생각했어요. 

빠른 첫 로딩 속도와 SEO 를 위해 SSR 방식을 택했어요!

### 코드 재사용
- [x] 기존 서비스에서 구현한 리액트 컴포넌트의 재사용 여부와 활용 방식에 대해 설명

기존 코끼리끼리에서 사용한 컴포넌트를 가져와서 썼지만, styled-components 는 직접 적용도 해봤지만 여러 이슈가 많더군요..!

2023-10-13 04:58 UTC, suyoungj requested changes
안녕하세요 부엉이~~ 
먼저 생일 축하드립니다 🎉🎉
생일 축하와 코드 리뷰를 같이 남기니 기분이 오묘하네요ㅋㅋㅋ
아래는 가이드라인을 따라 남긴 피드백입니다!

- 사용성: 인터랙션은 없는 페이지지만, '자세히 보기' 버튼과 같은 경우에는 `cursor: pointer`와 hover 효과 정도를 추가해줘도 좋을 것 같습니다!
- 데이터 요청: 서버 컴포넌트를 활용해서 데이터를 잘 불러와주신것 같네요!
- 에러 핸들링: 현재는 404, error 처리를 위한 컴포넌트가 존재하지 않는데, 
[not-found](https://nextjs.org/docs/app/api-reference/file-conventions/not-found), [error](https://nextjs.org/docs/app/api-reference/file-conventions/error)를 참고하셔서 추가해주시면 좋을 것 같습니다!

이외에 사소한 코멘트 몇 개 남겼습니다.
바쁘신 와중에 미션하시느라 고생 많으셨어요 👍

2023-10-13 04:58 UTC, suyoungj commented on src/components/roadmap/roadmapList/RoadmapList.module.css
> +    grid-template-columns: 1fr 1fr 1fr;
```css
grid-template-columns: repeat(3, 1fr);
```
로 쓸 수도 있겠네요!

2023-10-13 04:58 UTC, suyoungj commented on src/lib/registry.tsx
styled-components 적용 쉽지않네요.. 고생하셨습니다 🥲

2023-10-13 04:58 UTC, suyoungj commented on src/constants/categories.ts
> +  1: {
혹시 index와 id가 같이 존재하는 이유가 있을까요?

2023-10-15 07:40 UTC, sh981013s commented on src/components/roadmap/roadmapList/RoadmapList.module.css
> +    grid-template-columns: 1fr 1fr 1fr;
맞네요!! 완전 까먹고 있었네요 ㅎㅎ 👍

2023-10-15 07:40 UTC, sh981013s commented on src/lib/registry.tsx
🥲🥲🥲

2023-10-15 07:43 UTC, sh981013s commented on src/constants/categories.ts
> +  1: {
데이터 무결성: 데이터가 수정되거나 삭제될 때, id는 일관성을 유지하는 데 도움을 주지만. 반면에 index는 배열이나 목록 내의 위치를 나타내요!

정렬과 필터링: id와 index는 정렬이나 필터링에 사용될 수 있으나, id는 보통 무작위 생성되는 경우가 많아 정렬이나 필터링에 적합하지 않을다 생각합니다!  그에 반해 index는 순서를 나타내므로 이러한 작업에 더 적합할 수 있다 느꼈어요!

2023-10-15 08:00 UTC, sh981013s commented
유스 생일 축하해주셔서 감사합니다! 리뷰도 감사드리고요! 😁

유스의 리뷰를 받고 [not-found](https://nextjs.org/docs/app/api-reference/file-conventions/not-found), [error](https://nextjs.org/docs/app/api-reference/file-conventions/error) 컴포넌트를 추가로 구현 후 적용해보았습니다!!

잘 부탁드려요! 🙇‍♂️

2023-10-16 02:17 UTC, suyoungj approved these changes
안녕하세요 부엉이~~
수정사항 확인했습니다!
특별히 더 코멘트 할 점은 없어서 이만 머지하겠습니다
마지막 미션도 화이팅입니다!!

2023-10-16 02:17 UTC, merged