[팀 서비스 클론 코딩] 도리(남상규) 미션 제출합니다.
woowacourse/frontend-rendering pull request #31
Opened 2023-10-11 07:28 UTC by tkdrb12

# 🎨 1단계 - 팀 서비스의 일부 페이지 클론 코딩

## 🚀 구현한 페이지의 주소와 방식
- 주소: [https://frontend-rendering-2hks.vercel.app/]()
- 렌더링 방식: SSR

## ✅ 체크리스트

### 선택한 렌더링 방식의 이유

제가 구현한 페이지는 `게시물 목록 페이지`, `게시물 상세 조회 페이지` 두가지로 목록 페이지에서 게시물을 클릭하면 해당 게시물의 id값을 통해 게시물 상세 조회 페이지로 라우팅되는 방식입니다.
따라서 사용자가 게시물을 클릭해 상세 조회 게시물 데이터를 요청하는 시점에 상세 게시물 페이지의 렌더링이 필요하므로 `SSR`방식을 사용했습니다.

### 코드 재사용
스타일은 기존 서비스에서 사용하던 styled-components를 사용하였습니다. 하지만 registry설정을 해주거나 js과 스타일 파일을 분리해야 하는 등 생각보다 적용이 까다로웠습니다ㅠㅜ 괜히 Tailwind CSS를 권장하는 게 아니더라구요...

### 궁금한 점
<img width="937" alt="스크린샷 2023-10-11 오후 4 16 31" src="https://github.com/woowacourse/frontend-rendering/assets/103256030/0939b305-895c-46c2-9542-c5208b4a3825">

페이지를 이동하기 위해 위 컴포넌트인 RunnerPostItem에 onClick 이벤트를 달아놓을 필요가 있었는데요 onClick 이벤트를 사용하기 위해서는 해당 컴포넌트에 `use client`를 선언할 필요가 있었습니다.

해당 컴포넌트에  `use client`를 사용한다면 SSR적용이 정상적으로 되지 않아 자바스크립트 사용을 중지할 경우 RunnerPostItem 컴포넌트가 보이지 않을 줄 알았는데 보이더라구요?!? 

제가 생각하기로는 `use client`를 사용하면 일단 클라이언트 컴포넌트라 하더라도 초기값으로 렌더링 된 이후 Hydrate를 통해 렌더링된 데이터가 업데이트 되기 때문에 자바스크립트를 끄더라도 정상적으로 작동한 것 처럼 보인 것 같은데 제가 생각한게 맞을까요?

2023-10-14 03:22 UTC, ukkodeveloper requested changes
안녕하세요 도리! 우코입니다! 미션하느라 고생 많으셨어요!!

우선 기존 프로젝트에서 컴포넌트 재사용, 에러핸들링, 데이터 fetch 등 적절하게 잘 사용해주신 것 같습니다. 도리 코드 보면서 많이 배웠어요!!

### 도리가 궁금한점

> 페이지를 이동하기 위해 위 컴포넌트인 RunnerPostItem에 onClick 이벤트를 달아놓을 필요가 있었는데요 onClick 이벤트를 사용하기 위해서는 해당 컴포넌트에 `use client`를 선언할 필요가 있었습니다.
해당 컴포넌트에 `use client`를 사용한다면 SSR적용이 정상적으로 되지 않아 자바스크립트 사용을 중지할 경우 RunnerPostItem 컴포넌트가 보이지 않을 줄 알았는데 보이더라구요?!?
제가 생각하기로는 `use client`를 사용하면 일단 클라이언트 컴포넌트라 하더라도 초기값으로 렌더링 된 이후 Hydrate를 통해 렌더링된 데이터가 업데이트 되기 때문에 자바스크립트를 끄더라도 정상적으로 작동한 것 처럼 보인 것 같은데 제가 생각한게 맞을까요? 

[공식문서](https://nextjs.org/docs/app/building-your-application/rendering/client-components#how-are-client-components-rendered)에 따르면 Client Component라고 하더라도 자바스크립트 번들을 다운로드 하기 전에 HTML을 그려준다고 합니다. 도리가 말씀하셨던 것처럼 `RunnerPostItem`라 잘 보이는 게 정상입니다! 대신에 JS를 불러올 수 없으니 클릭 이벤트는 먹질 않을 거에요. 실제로 확인해보니 클릭 이벤트는 발생하지 않더라고요! 

저도 도리 덕분에 조금 찾아본 결과, “use client”가 CSR을 사용하겠다는 의미가 아닌 것 같아요! “use client”는 리액트의 서버 컴포넌트를 사용하지 않겠다라는 의미입니다. “use client”를 사용하더라도 SSR로 렌더링되지 않을까 싶네요! 

그 외에는 커멘트로 남겨두었습니다! 이미 충분히 잘해주셔서 코드 변경보다는 주로 궁금한 것들에 대한 질문이에요! 고생하셨습니다!도리 👍

2023-10-14 03:22 UTC, ukkodeveloper commented on src/app/layout.tsx
> +};
meta 태그도 변경해보면 좋을 것 같아요! 
SEO가 SSR을 사용하는 이유 중에 상당히 큰 비중이라고 생각이 들거든요! 저는 이번 미션에서 단일 페이지로 구현했지만, 도리는 포스팅 페이지도 구현을 해놓으셨기 때문에, 페이지마다 메타 데이터가 어떻게 변경되는 지 확인해보는 것도 큰 도움이 될 것 같습니다. [공식문서](https://nextjs.org/docs/app/building-your-application/optimizing/metadata)에 따르면 page에서 선언된 메타 정보들이 layout에 있는 메타 정보들을 속성별로 덮어쓰는 것 같더라고요! 👍

2023-10-14 03:22 UTC, ukkodeveloper commented on src/app/GlobalStyles.ts
> +'use client';
공식문서에 따르면 ㅋㅋㅋ (이 말 너무 많이 쓰는 것 같네요 )

> This means that by defining a "use client" in a file, all other modules imported into it, including child components, are considered part of the client bundle.

"use clinet"를 사용하면 그 하위에 있는 컴포넌트들은 클라이언트 컴포넌트로 취급되는 것 같더라고요. 그래서 중첩된 컴포넌트 구조에서 처음 "use client"를 사용한 부분을 기준으로 경계(Boundary)라는 표현을 사용하더라고요. 

그러면 제 추측으로는 도리가 선언한 서버 컴포넌트('use client'를 붙이지 않은 컴포넌트)도 클라이언트 컴포넌트로 작동할 것 같다는 생각이 들거든요. 이 부분 어떻게 생각하시는 지 궁금해요

2023-10-14 03:22 UTC, ukkodeveloper commented on src/app/runnerPost/[runnerPostId]/error.tsx
> +import { useRouter } from 'next/navigation';
현재 코드에서 useRouter을 사용하지 않는 것으로 보아 useRouter에서 Link로 변경하신 것 같은데, 그 이유가 있을까요?

2023-10-14 03:22 UTC, ukkodeveloper commented on src/lib/registry.tsx
> +'use client';
오... 저는 next13에서 css in js 가 제대로 작동하지 않아서 모두 module.css로 변경했었거든요. 이러한 방법이 있었군요. 혹시 이렇게 해당 코드가 어떤 일을 하는 건지 간단하게나마 설명해주실 수 있나요?

2023-10-14 03:22 UTC, ukkodeveloper commented on src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
> +    <S.RunnerPostItemContainer onClick={() => router.push(postUrl)}>
Link대신에 router.push를 사용하신 이유가 있을까요? 공식문서 보니 prefetch와 cache 기능을 강조하고 있는 것 같더라고요! 도리 프로젝트에서 prefetch와 cache를 어떻게 활용할 수 있을 지도 궁금해요!

2023-10-16 02:08 UTC, tkdrb12 commented on src/app/runnerPost/[runnerPostId]/error.tsx
> +import { useRouter } from 'next/navigation';
따로 이유는 없고 useRouter기능을 활용해보고 싶어 useRouter사용했었습니다 🥲
하지만 item컴포넌트 클릭 시 페이지 이동 외에는 다른 기능을 하고 있지 않으므로 link사용하는 게 더 적합해 보이네요!!
바로 link를 사용하도록 수정했습니다

2023-10-16 02:12 UTC, tkdrb12 commented on src/lib/registry.tsx
> +'use client';
registry를 사용하면 서버 렌더링 중에 스타일이 전역 레지스트리로 추출되어 'useServerInsertedHTML' 훅을 이용해서 <head>HTML로 삽입시킨다고 하네요! 이런식으로 스타일을 따로 추출해내는 기능을 하는 것 같아요!

2023-10-16 04:36 UTC, tkdrb12 commented on src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
> +    <S.RunnerPostItemContainer onClick={() => router.push(postUrl)}>
link에 prefetch 기능이 있는 지 몰랐었어요 link를 사용하면 미리 가져올 가능성이 있는 페이지에 대해 html을 미리 가져오는 prefetch를 수행하고 있었군요! 덕분에 next js의 라우팅 기능에 대해 공부할 수 있었어요!!

2023-10-16 04:52 UTC, tkdrb12 commented on src/app/GlobalStyles.ts
> +'use client';
맞아요 'use client'를 사용 시 해당 컴포넌트와 그 하위 컴포넌트의 자바스크립트 코드를 클라이언트 번들에 추가하는 과정이 있었습니다!
하지만 그 예외로 provider과 같이 클라이언트 컴포넌트 하위에 서버 컴포넌트를 둘 때 어떻게 작성해야 하는 지도 공식문서에 있더라구요!!
```
'use client'

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ThemeContext.Provider value="dark">{children}</ThemeContext.Provider>
      </body>
    </html>
  )
}
```

다음과 같이 서버 컴포넌트를 받아 래핑 해주는 패턴의 경우 클라이언트 컴포넌트 하위에 서버 컴포넌트를 둘 수 있는 것 같습니다! 

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns

2023-10-16 04:54 UTC, tkdrb12 commented on src/app/layout.tsx
> +};
SSR 렌더링의 방식에서 메타 데이터를 수정할 수 있는 것도 하나의 큰 이점이군요!! 
CSR과 비슷하니 별로 중요하지 않는 부분이라고 생각해서 넘어갔는데 중요한 부분을 놓쳐버릴 뻔 했습니다...👍

2023-10-16 06:07 UTC, ukkodeveloper approved these changes
반영사항 잘 확인했습니다! 도리 덕분에 저도 많이 공부할 수 있었네요! 2단계도 화이팅입니

2023-10-16 06:07 UTC, merged