[팀 서비스 클론 코딩] 유스(정수영) 미션 제출합니다.
woowacourse/frontend-rendering pull request #32
Opened 2023-10-11 07:34 UTC by suyoungj

안녕하세요 클린~~ 리뷰 잘 부탁드립니다 🙇🏻‍♂️
수많은 배포 에러 시도의 흔적으로 커밋 로그가 굉장히 지저분합니다.. 양해 부탁드려요 🥲
(사실 코드 상에는 문제가 없고 Vercel 프로젝트 세팅에 문제가 있었습니다 😂)

# 🎨 1단계 - 팀 서비스의 일부 페이지 클론 코딩

## 🚀 구현한 페이지의 주소와 방식
- 주소: [팀바팀 by Next.js](https://frontend-rendering-eosin.vercel.app/)
- 렌더링 방식: SSG

## ✅ 체크리스트

### 선택한 렌더링 방식의 이유
- 캘린더 페이지에 인터랙션을 제거하고, SSG 방식으로 렌더링하는 방식을 선택했습니다.
- 만약 일정에 대한 데이터가 고정되어있고, 사용자가 추가/삭제와 같은 인터랙션을 하지 않는다면 
SSG 방식으로 사용자에게 좀 더 빠르게 보여줄 수 있다는 생각이 듭니다. (사실 적합하다는 생각은 잘 들지 않네요 😅)
- Next.js 13, App Router, SSG (+트러블 슈팅)에 대해 학습해볼 수 있어서 뜻깊었던 미션이었던 것 같네요!

### 코드 재사용
- 헤더, 네비게이션 바, 캘린더와 관련된 컴포넌트를 재사용했습니다.
- 스타일링의 경우, styled-components를 사용하지 않고 css module로 처리했습니다.

2023-10-12 05:17 UTC, hozzijeong requested changes
안녕하세요 유스~ 테코톡 발표 잘 봤습니다!@!@

캘린더 페이지를 구현해 주셨군요~! 고생하셨습니다!!

- [x] 사용성: 페이지 기능이 잘 작동하네요@ 인터렉션이 안되는 점은 아쉽지만... 그래도 페이지로써의 기능은 잘 동작 하는것 같습니다!
- [x] 데이터 요청: 딱 fetch만을 사용해서
- [ ]  파일 기반 라우팅: 페이지 컴포넌트를 APP 폴더 안에서 넣으면 좀 더 좋았을 것 같아요~
- [ ]  에러 핸들링: error.js페이지를 만들어 주신 것을 확인했습니다! 그런데 [공식 문서](https://nextjs.org/docs/app/building-your-application/routing/error-handling)를 좀더 참조해서 에러 페이지를 만들면 좀 더 좋을 것 같아요!! (이 부분 역시 저도 해야 합니다 하하)

추가적으로 유스가 미션을 하면서 어떤 트러블 슈팅을 겪었는지 공유해 주시면 좋을 것 같아요!! 

고생하셨습니다!@!@

2023-10-12 05:17 UTC, hozzijeong commented on src/app/error.tsx
> +export default Error;
이 페이지에서도 use client를 사용할 이유가 있나요??

2023-10-12 05:17 UTC, hozzijeong commented on src/components/CalendarPage/CalendarPage.tsx
페이지 컴포넌트를 따로 분리한 이유가 있을까요? 

[공식 문서](https://nextjs.org/docs/app/api-reference/file-conventions/page)에서 말하는 컨벤션 처럼 페이지로 분리할 수 있는 부분은 페이지로 분리해 보는게 어떤가요?

2023-10-12 05:17 UTC, hozzijeong commented on src/app/layout.tsx
> +          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable-dynamic-subset.css"
폰트 멋져요 👍

Nextjs에서 폰트 최적화 관련 옵션을 제공하는걸로 알고 있는데 CDN으로 폰트를 다운받은 이유가 있을까요?

2023-10-12 05:17 UTC, hozzijeong commented on src/app/api/schedules/route.ts
> +  return NextResponse.json(schedules);
NextResponse를 사용하신 이유가 있나요??

2023-10-12 05:17 UTC, hozzijeong commented on bun.lockb
이건 뭐죵⁇⁇⁇

2023-10-12 05:17 UTC, hozzijeong commented on src/app/error.tsx
> +export default Error;
추가적으로 에러 페이지에 리셋이나 에러를 나타내는 등의 처리를 해주면 좋을 것 같아요! [여기](https://nextjs.org/docs/app/building-your-application/routing/error-handling)

2023-10-12 08:45 UTC, solo5star commented on bun.lockb
bun을 쓰시나요 👀 궁금궁금

2023-10-12 08:47 UTC, jeongwusi commented on bun.lockb
![image](https://github.com/woowacourse/frontend-rendering/assets/122500517/d6ec849d-8550-4822-a936-94104042ece6)

2023-10-12 08:47 UTC, jeongwusi commented on bun.lockb
![image](https://github.com/woowacourse/frontend-rendering/assets/122500517/26ef5b4b-9f3c-4061-a2b0-a596628e89c7)

2023-10-13 05:36 UTC, suyoungj commented on src/app/error.tsx
> +export default Error;
[error](https://nextjs.org/docs/app/building-your-application/routing/error-handling)를 확인해보니 error 컴포넌트는 Client 컴포넌트여야 한다고 하네요! 그래서 `use client`를 사용했습니다.

추가적으로 에러 메시지를 보여주고, 버튼 클릭 시 reset 로직을 추가했습니다.

2023-10-13 05:36 UTC, suyoungj commented on src/components/CalendarPage/CalendarPage.tsx
불필요한 컴포넌트였네요! 코멘트 감사합니다 👍

page 컴포넌트 내부로 fetch 로직을 옮기고, CalendarPage 컴포넌트를 제거했습니다.

2023-10-13 05:36 UTC, suyoungj commented on src/app/layout.tsx
> +          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable-dynamic-subset.css"
로컬 폰트 + Font 컴포넌트를 활용하면 최적화가 가능한 것으로 알고 있지만, 시간 절약을 위해 CDN으로 다운받는 방식을 선택했습니다 😅

2023-10-13 05:36 UTC, suyoungj commented on src/app/api/schedules/route.ts
> +  return NextResponse.json(schedules);
이런게 있구나 싶어서 한 번 사용해 보았습니다!

NextResponse가 제공하는 부가적인 기능을 활용하지는 않아서 제거하고, Response로 수정했습니다!

2023-10-13 05:37 UTC, suyoungj commented on bun.lockb
나온지 얼마 되지 않은 따끈한 Javascript Runtime입니다!

https://bun.sh/

전 node와 npm 대신 사용하고 있는데, 가끔씩 빠른게 체감되긴 하더라구요.
관심있으시면 한 번 사용해보셔도 좋을 것 같습니다!

2023-10-13 05:40 UTC, suyoungj commented
리뷰 감사합니다 클린~~!!
이번에 배포를 했는데 404 페이지가 계속 나오더라구요 😂

![image](https://github.com/woowacourse/frontend-rendering/assets/19235163/1a99facd-8e6e-4cce-a36c-663018ca798b)

Framework Preset이 Next.js가 아닌 Others로 되어있어서 발생한 문제였습니다.
사소하지만, 코드 밖에서 에러를 찾느라 시간을 되게 많이 썼어요..ㅋㅋㅋㅋ

2023-10-13 11:52 UTC, hozzijeong commented on bun.lockb
도전 정신이었군요!! 멋있습니다 저도 시간되면 한번 사용해 봐야겠네요 ㅎ

2023-10-14 00:39 UTC, hozzijeong approved these changes
안녕하세요 유스! 변경사항 확인했습니다

앞서 리뷰드렸던 라우팅 방식을 파일 기반으로 변경한 것과 에러 페이지를 통해서 핸들링 하는 부분까지 잘 봤습니다!! 페이지가 하나라 약간 아쉬운 감이 없지 않게 있지만 그래도 어떤 의도로 확인했는지 잘 볼 수 있었어요!!

번을 사용하신 이유는 역시 도전 정신이었군요... 새롭게 출시되었다는 이야기는 들었는데 한번도 사용을 안해봐서 저도 기회가 되면 한번 사용해 봐야겠습니다 !! 

1단계 미션 하시느라 고생하셨습니다~~ 2단계 미션에서 봬요! 주말 잘 보내세요@

그럼 20000

2023-10-14 00:39 UTC, hozzijeong commented on src/app/error.tsx
크 좋아요 좋아요~!~! 

Next에서는 ErrorBoundary를 해당 페이지에서 바로 제공해준다고 하는데 이거 정말 좋은 것 같더라구요~

2023-10-14 00:40 UTC, merged