[렌더링 방식의 분석] 헤다(윤다혜) 미션 제출합니다.
woowacourse/frontend-rendering pull request #76
Opened 2023-10-16 08:45 UTC by Dahyeeee

# 🧐 2단계 - 렌더링 방식의 분석

🍫첵스~~ 마지막 미션으로 왔습니다!
마지막 미션이라니.. 시간이 빠른 듯!! 느린듯!! 뭐 그렇습니다.

1단계에서 2단계 미션을 미리 해놓아서 조금 수월하게 미션을 진행할 수 있었습니다. 
글밖에 없지만 지루하지 않았으면 좋겠군요. 떡볶이 비유도 재밌기를 바래봅니다.
[여기서 보면 쪼금 편함](https://github.com/Dahyeeee/frontend-rendering/blob/step2/STEP2.md)

마지막까지 잘 부탁드려요 :) 

## ✅ 체크리스트

### 렌더링 시점 비교
- [x] SPA와 본인이 선택한 렌더링 방식(SSR, SSG, ISR) 중 본인이 선택한 방식간의 렌더링 시점에 어떤 일이 벌어지는지 설명 (그림 또는 다이어그램 활용도 좋습니다)

### 사용자 경험(UX) 측면 분석
- [x] 각 렌더링 방식이 사용자 경험에 어떻게 영향을 미치는지 설명

### 성능 측정 및 비교
- [x] SPA와 본인이 선택한 렌더링 방식(SSR, SSG, ISR)의 성능을 측정하고 비교 (사용한 측정 도구나 방법을 명시)

2023-10-18 13:05 UTC, HyeryongChoi requested changes
헤다랑 렌더링 미션 토론 때 이미 이야기를 많이 나눠서 코멘트를 많이 달게 없었네요! 
질문 한 가지 달아봤습니다. 헤다도 궁금한 게 있다면 언제든지 말해주세요~~!

2023-10-18 13:05 UTC, HyeryongChoi commented on STEP2.md
> +여기는 떡볶이 집입니다.
무슨 떡볶이 집이죠? 엽떡인가요 신전떡볶이인가요? 아니면 청년다방인가요 아니면 우리할매떡볶이인가요?

2023-10-18 13:05 UTC, HyeryongChoi commented on STEP2.md
> +- 손님이 떡볶이를 주문하자 이미 끓여놓은 완성된 떡볶이를 대령합니다.
떡에 간이 배여서 맛이 딱 좋겠군요!

2023-10-18 13:05 UTC, HyeryongChoi commented on STEP2.md
> +- 단점: 주인이 주방에서 요리하느라 힘이 듭니다. 이미 서빙된 떡볶이에 손님이 대파를 추가할 수는 없습니다.
만약 사용자가 `/main` 경로(20개의 상품목록이 있는 페이지)에 접속 후 SSR방식으로 첫 페이지를 렌더링한 상황에서 '상품 더보기'라는 버튼을 클릭했을 때는 추가되는 상품 아이템 컴포넌트만 CSR방식으로 렌더링되기 때문에 '이미 서빙된 떡볶이에 손님이 대파를 추가할 수는 없습니다'인 것인가요?

그리고 또 궁금한 게 있어요~~
만약 사용자가 `/main` 경로(20개의 상품목록이 있는 페이지)에 접속 후 SSR방식으로 첫 페이지를 렌더링한 상황에서 222 -> 상품목록 데이터베이스에 '헤다의 텀블러'라는 상품이 추가 됐을 때 사용자는 새로고침하기 전까지는 볼 수 없는 건가용?

2023-10-18 13:05 UTC, HyeryongChoi commented on STEP2.md
> +- 손님이 집에 가서 재료를 넣고 떡볶이를 끓여 완성합니다.
비조리 떡볶이군요,,

2023-10-18 13:05 UTC, HyeryongChoi commented on STEP2.md
> +- SSG: 커뮤니티 페이지, 나의 여행 페이지 (revalidate 주기 10분 : 좋아요 기능이 있어서 자주 업데이트 해줘야 할 것 같습니다)
좋아요는 10분은 넘 긴 거 아닌가요? 실시간으로 반영되어야하지 않을까요? 홍홍

2023-10-23 01:28 UTC, Dahyeeee commented on STEP2.md
> +여기는 떡볶이 집입니다.
우리할매가 대존맛이니 우리할매떡볶이집이라고 하겠습니다 👍🏻

2023-10-23 01:29 UTC, Dahyeeee commented on STEP2.md
> +- 손님이 떡볶이를 주문하자 이미 끓여놓은 완성된 떡볶이를 대령합니다.
ㅋㅋㅋㅋㅋㅋㅋ 간이 밴 떡볶이 최고

2023-10-23 01:35 UTC, Dahyeeee commented on STEP2.md
> +- 단점: 주인이 주방에서 요리하느라 힘이 듭니다. 이미 서빙된 떡볶이에 손님이 대파를 추가할 수는 없습니다.
오 뭔가 생각해보지 못한 경우의 수 인데 첵스가 말한 게 맞는 것 같습니다!

SSR은 이미 데이터가 담겨서 그려진 페이지가 오기 때문에 그 부분에 새로운 데이터를 추가할 수는 없습니다.
그러나 '더보기'를 클릭했을 때 CSR로 페이지가 랜더링이 된다면 그 부분은 새로운 데이터가 들어오겠네요. 그렇지만 여기는 SSR이라고 보기 어렵겠지요?!

네네@ 클라이언트 쪽에서 데이터가 오래되었는지, 새로운 데이터가 추가되었는지 감지하고 해당상황에 데이터를 새로 불러오는 기능이 불가능하기 때문에 새로고침을 하지 않는 한 '헤다의 텀블러'는 볼 수 없습니다!

2023-10-23 01:35 UTC, Dahyeeee commented on STEP2.md
> +- 손님이 집에 가서 재료를 넣고 떡볶이를 끓여 완성합니다.
옴뇸뇸 떡뽁이

2023-10-23 01:36 UTC, Dahyeeee commented on STEP2.md
> +- SSG: 커뮤니티 페이지, 나의 여행 페이지 (revalidate 주기 10분 : 좋아요 기능이 있어서 자주 업데이트 해줘야 할 것 같습니다)
듣고보니 그런 거 같군요 
인스타처럼 유저가 대박 많지 않아서 안일하게 생각했습니다 호홓

2023-10-23 01:37 UTC, Dahyeeee commented
첵스 질문 덕분에 새롭게 고민하고 알아보았습니다~ 재밋군요
마지막 미션 마지막 리뷰어로 만나서 아주 좋앗씁니다 첵스~ 
이렇게 오타내고 수정안해도 맘 편한 첵스~~

마지막까지 고마워요~~🥰

2023-10-23 01:50 UTC, HyeryongChoi approved these changes
@Dahyeeee 

즐거왓습니다 해다 오타를 내도 수정하지 않아도 된대니 저도 조내요~*^^*
마지막 미션에서 리뷰어-리뷰이로 헤다랑 만나서 조앗읍니다.
헤다가 제로의 여정을 응원하는 매새지를 남겼던데 저도 해다의 여정 늘 응원하갯습니다.
혀다 파이팅!! 👏😄

2023-10-23 01:51 UTC, merged