[렌더링 방식의 분석] 우스(김영길) 미션 제출합니다.
woowacourse/frontend-rendering pull request #86
Opened 2023-10-16 08:58 UTC by Gilpop8663

# 🧐 2단계 - 렌더링 방식의 분석

안녕하세요 루루! 2단계 빠르게 만나게 되었네요

개발 서버가 망가져서 성능 비교를 다 못쓰게 되었는데요. 복구되면 성능 비교 글을 마저 작성해보도록 하겠습니다.

그리고 렌더링 방식에 대해서 글을 작성하다 보니깐 너무 헷갈리더라구요 특히 SSR이 헷갈렸습니다.

서버에서 데이터 패치를 해서 HTML을 그려서 보내주는 것으로 이해하기로 했어요

### <a href="https://github.com/Gilpop8663/frontend-rendering/blob/step2/README.md">README 보러가기</a>

2023-10-17 01:46 UTC, hafnium1923 requested changes
깔끔하게 그림으로 렌더링 방법 정리해주셔서 저도 이해하기 편했어요!
궁금한 부분 하나 있어서 댓글달았어요! 
만약 성능 분석하실거면 성능 분석까지 완료되고 나서 리뷰요청해주시면 깔끔할 것 같아요.
성능 분석 안하시면 그냥 답글만 달아주셔도 좋아요! 

수고하셨습니다🥳🥳🥳

2023-10-17 01:46 UTC, hafnium1923 commented on README.md
> +SSR : 매번 변하는 데이터가 있을 때 서버에서 패치해와서 그려준 HTML과 CSS를 주고, 클라이언트 컴포넌트에 사용되는 javascript 파일을 다운받아 사용자에게 보여줍니다. 미리 서버에서 그려준 뒤 보내주기 때문에 자바스크립트 용량을 줄일 수 있고, 사이트의 모든 페이지에서 필요한 파일이 아닌 해당 페이지가 필요한 파일만 보내줘서 초기 렌더링
이건 제 궁금증인데요, 클라이언트 컴포넌트가 있어도 SSR로 동작할 수 있는건가요? 그러면 컴포넌트들의 최상단만 server component로 구현해두면 그 하위 컴포넌트는 다 클라이언트 컴포넌트여도 상관없는거 아닌가 싶어서요

2023-10-17 04:58 UTC, Gilpop8663 commented on README.md
> +SSR : 매번 변하는 데이터가 있을 때 서버에서 패치해와서 그려준 HTML과 CSS를 주고, 클라이언트 컴포넌트에 사용되는 javascript 파일을 다운받아 사용자에게 보여줍니다. 미리 서버에서 그려준 뒤 보내주기 때문에 자바스크립트 용량을 줄일 수 있고, 사이트의 모든 페이지에서 필요한 파일이 아닌 해당 페이지가 필요한 파일만 보내줘서 초기 렌더링
클라이언트 컴포넌트가 있어도 SSR로 동작이 가능하다고 이해했어요.  대신 use client가 붙은 컴포넌트는 자바스크립트 파일이 전부 로드되기 전에는 화면에 미리 그려져있어도 동작은 되지 않는다고 해요. 그래서 최상단에 server component로 구현해두고 하위로 props를 통해 구현한다면 클라이언트 컴포넌트여도 상관 없다고 생각이 들어요

2023-10-19 05:29 UTC, hafnium1923 commented
우스우스 수고많았어요~! 데모데이 준비하면서 바쁘셨을 텐데 꼼꼼한 답변 감사해요
내용도 충분해서 더이상 물어볼 곳이 없네요ㅋㅋ
마지막 미션인데 수고 많으셨어요!!

내일봐요🥳

2023-10-19 05:29 UTC, merged